# If you agree with eula witch is down then type eula: true
eula: false

# EULA:
# Using IP address can only be used to see if someone is hacking someone else
# THIS PLUGIN CANNOT BE USED TO STEAL IPS DOING THAT IS FULLY ILLEGAL!
# USING THIS PLUGIN IN ANY OTHER WAY IS ILLEGAL AND ANYONE ON THE SERVER MUST KNOW YOU HAVE THEY'RE IP!